version: "3.6"
services:
  beacon-validator:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v22.6.0
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      LOG_TYPE: INFO
      HTTP_ENGINE: "http://nethermind-xdai.dappnode:8551"
      GRAFFITI: validating_from_DAppNode
      P2P_TCP_PORT: 19006
      P2P_UDP_PORT: 19006
      WEB3_BACKUP: "https://rpc.gnosischain.com/"
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
    ports:
      - "19006:19006/tcp"
      - "19006:19006/udp"
    volumes:
      - "nimbus-gnosis-data:/home/user/nimbus-eth2/build/data"
    image: "beacon-validator.nimbus-gnosis.dnp.dappnode.eth:0.1.0"
volumes:
  nimbus-gnosis-data: {}
