version: "3.6"
services:
  beacon-validator:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v22.10.0
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      LOG_TYPE: INFO
      HTTP_WEB3PROVIDER: "http://nethermind-xdai.dappnode:8545"
      GRAFFITI: validating_from_DAppNode
      WEB3_BACKUP: "https://rpc.gnosischain.com/"
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
    ports:
      - 9000/tcp
      - 9000/udp
    volumes:
      - "nimbus-gnosis-data:/home/user/nimbus-eth2/build/data"
    image: "beacon-validator.nimbus-gnosis.dnp.dappnode.eth:0.1.0"
volumes:
  nimbus-gnosis-data: {}
